--- #YAML:1.0
name:                File-Monitor-Lite
version:             0.652002
abstract:            Monitor file changes
license:             ~
author:              
    - dryman <dryman@apple.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Class::Accessor::Fast:         0
    File::Find::Rule:              0
    File::Monitor:                 0
    File::Spec::Functions:         0
    File::Touch:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
